### ISSUE TITLE
Opencv with quirc support

### ISSUE THREAD

**Issue by ghost** [rajeshpachaikani/QR-Reader-Rust-OpenCV-Demo#1]
Hello,
I wanna test your code, but on my device ( ubuntu)  its saying, that i have no install opencv with quirc. Is possible to get this opencv via official repository ? or i must compile on myself on that device with -D WITH_QUIRC=ON ?
thanks

**Comment by rajeshpachaikani** [comment]
Unfortunately the libopencv-dev package in ubuntu repository don't have the QUIRC module enabled by default. You must compile opencv with QUIRC support. Let me know if you find any alternate ways for reading QR codes without QUIRC or without Opencv itself.
